language: python
install:
    - pip install -r requirements.txt
    - pip install coveralls
script: PYTHONPATH=src:$PYTHONPATH nosetests --with-coverage --cover-package=redmill tests
after_success: coveralls
